server:
  port: 8083

        
spring:
  application:
    name: api-gateway 
  cloud:
    gateway:
      routes:
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employees/**
        
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/departments/**
        
      - id: manager-service
        uri: lb://manager-service
        predicates:
        - Path=/managers/**